// Code generated by mockery. DO NOT EDIT.

// NOTE: run 'make mocks' to update this file and generate new ones.

package mocks

import (
	context "context"

	domain "github.com/chaewonkong/go-test-examples/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: c
func (_m *UserService) FindAll(c context.Context) ([]domain.User, error) {
	ret := _m.Called(c)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type UserService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - c context.Context
func (_e *UserService_Expecter) FindAll(c interface{}) *UserService_FindAll_Call {
	return &UserService_FindAll_Call{Call: _e.mock.On("FindAll", c)}
}

func (_c *UserService_FindAll_Call) Run(run func(c context.Context)) *UserService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserService_FindAll_Call) Return(_a0 []domain.User, _a1 error) *UserService_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FindOne provides a mock function with given fields: c, name
func (_m *UserService) FindOne(c context.Context, name string) (domain.User, error) {
	ret := _m.Called(c, name)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(c, name)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type UserService_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - c context.Context
//   - name string
func (_e *UserService_Expecter) FindOne(c interface{}, name interface{}) *UserService_FindOne_Call {
	return &UserService_FindOne_Call{Call: _e.mock.On("FindOne", c, name)}
}

func (_c *UserService_FindOne_Call) Run(run func(c context.Context, name string)) *UserService_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_FindOne_Call) Return(_a0 domain.User, _a1 error) *UserService_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserService(t mockConstructorTestingTNewUserService) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
